### PR TITLE
fix for generalized eigproblems

### PR DESCRIPTION
**Pull request by stevengj**
Rebased version of #4.

What needs to be done to get something in to fix this problem?

### CODE REVIEW

**Comment by andreasnoack** [comment]
@jarlebring @antoine-levitt What's you thinking on this here two years later? It would be great to get some fix in.

**Comment by antoine-levitt** [comment]
I always get confused with these ARPACK settings, but the PR looks fine. The main thing that changed from 2 years ago is that there are a number of high-quality pure-julia implementations, so there's no real need to bother with ARPACK anymore.

**Comment by jarlebring** [comment]
As I see it, two years ago the discussion got stuck partially on the kwarg-usage and what should be done automatically considering that users of the package would expect future versions to have the same kwargs.  In the meantime, beside good native Julia packages, MATLAB also removed their arpack dependence with their own matlab implementation.

**Comment by ViralBShah** [comment]
While certainly true there are many more options, I just decided to clean up a bunch of accumulated issues on this package just to keep it going. Seems like this is passing now. Should we merge?

**Comment by ViralBShah** [comment]
Going through the comments here, and the number of issues this fixes, it seems this is ok to merge. Let's fix other issues as they come up.

**Pull request merged**
